src/cart/urls.py
from django.urls import path
from cart import views


app_name = 'cart'

urlpatterns = [
    path('add-to-cart/', views.AddToCartView.as_view(), name='add-to-cart'),
    path('view-cart/', views.CartView.as_view(), name='view-cart'),
    path('update-cart/', views.UpdateCart.as_view(), name='update-cart'),
    path('delete-from-cart/<int:pk>/', views.DeleteFromCart.as_view(), name='delete-from-cart'),
]


# from django.urls import path
# from . import views

# app_name = 'cart'

# urlpatterns = [
#     path('add-to-cart/', views.UpdateCart.as_view(), name="add-to-cart"),
#     path('recalculate-cart/', views.RecalculateCart.as_view(), name="recalculate-cart")
# ]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as main_views
from references import urls as refs_urls
from users import urls as users_urls
from cart import urls as cart_urls


#from references.views import books_list
# from cart import views as cart_views


urlpatterns = [
    path('admin/', admin.site.urls), #http://127.0.0.1:8000/admin/
    path('', main_views.HomePage.as_view(), name='homepage'),
    path('books-catalog', main_views.BooksCatalog.as_view(), name='books-catalog'),
    path('references/', include(refs_urls, namespace='references')),
    path('users/', include(users_urls, namespace='users')),
    path('cart/', include(cart_urls, namespace='cart')),
    # path('books/', ref_views.BooksList.as_view(), name='books-list'),
    # path('books/<int:pk>/', ref_views.BookDetail.as_view(), name='book-detail'),
    # path('book-delete/<int:pk>/', ref_views.BookDelete.as_view(), name='book-delete'),
    # path('book-create/', ref_views.BookCreate.as_view(), name='book-create'),
    # path('book-update/<int:pk>/', ref_views.BookUpdate.as_view(),name="book-update"),
    # path('accs/', include(accs_urls)), 
    # path('cart/', include(cart_urls, namespace="cart")),
    # path('cart/', cart_views.HomePage.as_view(), name = "home-page")
    # path('home', ref_views.HomeList.as_view(), name='home'),
    # path('books/', views.books_list, name='books_list'), 
    # path('books/<int:pk>/', views.book_detail, name='book-detail'),
    # path('book-delete/<int:pk>/', views.book_delete, name='book-delete'),
    # path('book-create/', views.book_create, name='book-create'),
    # path('book-update/<int:pk>/', views.book_update, name='book-update'), 
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings .MEDIA_ROOT)  

    #path('books/<int:pk>', views.book_details)
    
    
#1.URL http://127.0.0.1:8000/cities/3/ (pk)
#2.GET http://127.0.0.1:8000/cities/?city_id=4...
#3.POST k:v, k:v    

src/references/urls.py
from django.urls import path
from . import views


app_name = 'references'

urlpatterns = [
    path('authors-list/', views.AuthorsList.as_view(), name='authors-list'),
    path('genres-list/', views.GenresList.as_view(), name='genres-list'),
    path('series-list/', views.SeriesList.as_view(), name='series-list'),
    path('publishers-list/', views.PublishersList.as_view(), name='publishers-list'),
    path('age_categories-list/', views.AgeCategoriesList.as_view(), name='age_categories-list'),
    # path('book_formats-list/', views.BookFormatsList.as_view(), name='book_formats-list'),

    path('authors-delete/<int:pk>/', views.AuthorsDelete.as_view(), name='authors-delete'),
    path('genres-delete/<int:pk>/', views.GenresDelete.as_view(), name='genres-delete'),
    path('series-delete/<int:pk>/', views.SeriesDelete.as_view(), name='series-delete'),
    path('publishers-delete/<int:pk>/', views.PublishersDelete.as_view(), name='publishers-delete'),
    path('age_categories-delete/<int:pk>/', views.AgeCategoriesDelete.as_view(), name='age_categories-delete'),
    # path('book_formats-delete/<int:pk>/', views.BookFormatsDelete.as_view(), name='book_formats-delete'),
    
    path('authors-update/<int:pk>/', views.AuthorsUpdate.as_view(), name='authors-update'),
    path('genres-update/<int:pk>/', views.GenresUpdate.as_view(), name='genres-update'),
    path('series-update/<int:pk>/', views.SeriesUpdate.as_view(), name='series-update'),
    path('publishes-update/<int:pk>/', views.PublishersUpdate.as_view(), name='publishers-update'),
    path('age_categories-update/<int:pk>/', views.AgeCategoriesUpdate.as_view(), name='age_categories-update'),
    # path('book_formats-update/<int:pk>/', views.BookFormatsUpdate.as_view(), name='book_formats-update'),
    
    path('authors-create/', views.AuthorsCreate.as_view(), name='authors-create'),
    path('genres-create/', views.GenresCreate.as_view(), name='genres-create'),
    path('series-create/', views.SeriesCreate.as_view(), name='series-create'),
    path('publishers-create/', views.PublishersCreate.as_view(), name='publishers-create'),
    path('age_categories-create/', views.AgeCategoriesCreate.as_view(), name='age_categories-create')
    # path('book_formats-create/', views.BookFormatsCreate.as_view(), name='book_formats-create')
]

src/references/forms.py
from django import forms
from references import models


class AuthorForm(forms.ModelForm):
    class Meta:
        model = models.Authors
        fields = ['name']
    

class GenreForm(forms.ModelForm):
    class Meta:
        model = models.Genres
        fields = ['name']


class SeriesForm(forms.ModelForm):
    class Meta:
        model = models.Series
        fields = ['name']


class PublisherForm(forms.ModelForm):
    class Meta:
        model = models.Publishers
        fields = ['name']


class AgeCategoriesForm(forms.ModelForm):
    class Meta:
        model = models.AgeCategories
        fields = ['name']


# class BookFormatsForm(forms.ModelForm):
#     class Meta:
#         model = models.BookFormats
#         fields = ['name']








# from django import forms
# from django.db.models import fields
# from . import models

# class BookForm (forms.ModelForm):
#     class Meta:
#         model = models.Book 
#         # fields = ('__all__')
#         fields = ('book_name', 'pic', 'book_description' )

# class SearchForm(forms.Form):
#     q = forms.CharField(label="Search:") #query(?)
#     field=forms.CharField(widget=forms.HiddenInput)
#     direction=forms.CharField(widget=forms.HiddenInput)



    # def clean(self):
    #     cleaned_data = super().clean()
    #     name = cleaned_data.get ('name')

    #     if name == "Yaroslav":
    #         self.add_error('name', 'This name is forbidden')
    #     return cleaned_data
    
    #name = forms.CharField(
    #    max_length=50,
    #    required=True,
    #    label="Author's name",
    #    help_text="Input some name"
    #)
    
    #description = forms.CharField(
    #    label="Author's description",
    #    required=False,
    #    widget=forms.Textarea
    #)

    

src/references/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from references import models, forms
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

# Create your views here.
# Dictionaries ListViews
class AuthorsList(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    paginate_by = 10
    login_url = reverse_lazy('login')
    permission_required = 'references.view_authors'
    model = models.Authors
    template_name = 'references/list_authors.html'
    

class GenresList(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    paginate_by = 10
    login_url = reverse_lazy('login')
    permission_required = 'references.view_genres'
    model = models.Genres
    template_name = 'references/list_genres.html'
    

class SeriesList(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    paginate_by = 10
    login_url = reverse_lazy('login')
    permission_required = 'references.view_series'
    model = models.Series
    template_name = 'references/list_series.html'


class PublishersList(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    paginate_by = 10
    login_url = reverse_lazy('login')
    permission_required = 'references.view_publishers'
    model = models.Publishers
    template_name = 'references/list_publishers.html'


class AgeCategoriesList(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    paginate_by = 10
    login_url = reverse_lazy('login')
    permission_required = 'references.view_agecategories'
    model = models.AgeCategories
    template_name = 'references/list_age_categories.html'


# class BookFormatsList(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
#     paginate_by = 10
#     login_url = reverse_lazy('login')
#     permission_required = 'references.view_bookformats'
#     model = models.BookFormats
#     template_name = 'references/list_book_formats.html'


# references generic.DeleteViews
class AuthorsDelete(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    login_url = reverse_lazy('login')
    permission_required = 'references.delete_authors'
    model = models.Authors
    template_name = 'references/form_confirm_delete.html'
    success_url = reverse_lazy('authors-list')


class GenresDelete(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    login_url = reverse_lazy('login')
    permission_required = 'references.delete_genres'
    model = models.Genres
    template_name = 'references/form_confirm_delete.html'
    success_url = reverse_lazy('genres-list')


class SeriesDelete(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    login_url = reverse_lazy('login')
    permission_required = 'references.delete_series'
    model = models.Series
    template_name = 'references/form_confirm_delete.html'
    success_url = reverse_lazy('series-list')


class PublishersDelete(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    login_url = reverse_lazy('login')
    permission_required = 'references.delete_publishers'
    model = models.Publishers
    template_name = 'references/form_confirm_delete.html'
    success_url = reverse_lazy('publishers-list')


class AgeCategoriesDelete(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    login_url = reverse_lazy('login')
    permission_required = 'references.delete_agecategories'
    model = models.AgeCategories
    template_name = 'references/form_confirm_delete.html'
    success_url = reverse_lazy('age_categories-list')


# class BookFormatsDelete(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
#     login_url = reverse_lazy('login')
#     permission_required = 'references.delete_bookformats'
#     model = models.BookFormats
#     template_name = 'references/form_confirm_delete.html'
#     success_url = reverse_lazy('boo_formats-list')


# references UpdateViews
class AuthorsUpdate(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    login_url = reverse_lazy('login')
    permission_required = 'references.change_authors'
    model = models.Authors
    form_class = forms.AuthorForm
    template_name = 'references/form_create_update.html'
    success_url = reverse_lazy('authors-list')


class GenresUpdate(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    login_url = reverse_lazy('login')
    permission_required = 'references.change_genres'
    model = models.Genres
    form_class = forms.GenreForm
    template_name = 'references/form_create_update.html'
    success_url = reverse_lazy('genres-list')


class SeriesUpdate(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    login_url = reverse_lazy('login')
    permission_required = 'references.change_series'
    model = models.Series
    form_class = forms.SeriesForm
    template_name = 'references/form_create_update.html'
    success_url = reverse_lazy('series-list')


class PublishersUpdate(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    login_url = reverse_lazy('login')
    permission_required = 'references.change_publishers'
    model = models.Publishers
    form_class = forms.PublisherForm
    template_name = 'references/form_create_update.html'
    success_url = reverse_lazy('publishers-list')


class AgeCategoriesUpdate(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    login_url = reverse_lazy('login')
    permission_required = 'references.change_agecategories'
    model = models.AgeCategories
    form_class = forms.AgeCategoriesForm
    template_name = 'references/form_create_update.html'
    success_url = reverse_lazy('age_categories-list')


# class BookFormatsUpdate(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
#     login_url = reverse_lazy('login')
#     permission_required = 'references.change_bookformats'
#     model = models.BookFormats
#     form_class = forms.BookFormatsForm
#     template_name = 'references/form_create_update.html'
#     success_url = reverse_lazy('book_formats-list')


# references CreateViews
class AuthorsCreate(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    login_url = reverse_lazy('login')
    permission_required = 'references.add_authors'
    model = models.Authors
    form_class = forms.AuthorForm
    template_name = 'references/form_create_update.html'
    success_url = reverse_lazy('authors-list')


class GenresCreate(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    login_url = reverse_lazy('login')
    permission_required = 'references.add_genres'
    model = models.Genres
    form_class = forms.GenreForm
    template_name = 'references/form_create_update.html'
    success_url = reverse_lazy('genres-list')


class SeriesCreate(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    login_url = reverse_lazy('login')
    permission_required = 'references.add_series'
    model = models.Series
    form_class = forms.SeriesForm
    template_name = 'references/form_create_update.html'
    success_url = reverse_lazy('series-list')


class PublishersCreate(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    login_url = reverse_lazy('login')
    permission_required = 'references.add_publishers'
    model = models.Publishers
    form_class = forms.PublisherForm
    template_name = 'references/form_create_update.html'
    success_url = reverse_lazy('publishers-list')


class AgeCategoriesCreate(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    login_url = reverse_lazy('login')
    permission_required = 'references.add_agecategories'
    model = models.AgeCategories
    form_class = forms.AgeCategoriesForm
    template_name = 'references/form_create_update.html'
    success_url = reverse_lazy('age_categories-list')


# class BookFormatsCreate(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
#     login_url = reverse_lazy('login')
#     permission_required = 'references.add_bookformats'
#     model = models.BookFormats
#     form_class = forms.BookFormatsForm
#     template_name = 'references/form_create_update.html'
#     success_url = reverse_lazy('book_formats-list')






# from django.shortcuts import render
# from django.http import HttpResponseRedirect
# from django.urls import reverse, reverse_lazy 
# from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
# from django.views.generic import DetailView, ListView, DeleteView, CreateView, UpdateView
# from django.db.models import Q
# from . import forms

# from references.models import Book

# # (UserPassesTestMixin, ListView) 

# class BooksList (LoginRequiredMixin, ListView) :
#    model = Book
#    login_url = '/admin/login/'
#    paginate_by = 10  #elements per page

#    def get_ordering(self):
#       ordering_by = "pk"
#       field_to_sort_on = self.request.GET.get('field')
#       direction_to_sort_on = self.request.GET.get ('direction')
#       if field_to_sort_on and direction_to_sort_on:
#          direction = {'up': ""}
#          ordering_by = f'{direction.get(direction_to_sort_on,"-")}{field_to_sort_on}'
#       return ordering_by
   
#       #    if direction_to_sort_on == 'up':
#       #       direction = ""
#       #    else:                  => ordering_by = f'{direction.get(direction_to_sort_on,"-")}{field_to_sort_on}'
#       #       direction = "-"  
#    # def get_queryset(self):
#    #    return super().get_queryset()

#    def get_queryset(self):
#       q = self.request.GET.get('q')
#       qs = super().get_queryset()
#       if q:
#          my_filter = Q(book_description__contains=q)|Q(book_name__contains=q)
#          qs = qs.filter(my_filter).distinct()
#       return qs

#    def get_context_data (self, **kwargs):
#       context = super().get_context_data (**kwargs)
#       context ['page_title'] = "Books"

src/references/templates/form_confirm_delete.html
{% extends "template_main.html" %}

{% block title %}
    Removing process
{% endblock title %}

{% block page_header %}
 {{ object.pk }} <b><i>({{ object}})</i></b> removing ?
{% endblock page_header %}

{% block main_content %}
    
    <br>

    <form action="" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger" >Delete</button>
        <a onclick="history.back()" class="btn btn-secondary" >Back</a>
    </form>
    
{% endblock main_content %}

src/references/templates/form_create_update.html
{% extends "template_main.html" %}

{% load crispy_forms_tags %}

{% block title %}
    Creation
{% endblock title %}

{% block page_header %}
    Enter the data below
{% endblock page_header %}

{% block main_content %}
    
    <br>

    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <button type="submit" class="btn btn-success" >Save</button>
        <button onclick="history.back()" class="btn btn-secondary" >Back</button>
        <!-- <button onclick="history.back()" class="btn btn-secondary" style="width: 200px;">Назад</button> -->
    </form>
    
{% endblock main_content %}

src/references/templates/list_age_categories.html
{% extends "references/list_template.html" %}

{% block title %}
    Age categories
{% endblock title %}

{% block page_header %}
    Age categories 
{% endblock page_header %}

{% block dict_actions %}
    <a title="Edit" href="{% url 'references:age_categories-update' object.pk %}"><i class="bi bi-pencil-square"></i></a>
    <a title="Delete" href="{% url 'references:age_categories-delete' object.pk %}"><i class="bi bi-trash"></i></a>
{% endblock dict_actions %}

{% block dict_create %}
    <a href="{% url 'references:age_categories-create' %}" class="btn btn-primary" >Add</a><br><br>
{% endblock dict_create %}

src/references/templates/list_authors.html
{% extends "references/list_template.html" %}

{% block title %}
    Authors
{% endblock title %}

{% block page_header %}
    Authors <br>
{% endblock page_header %}

{% block dict_actions %}
    <a title="Edit" href="{% url 'references:authors-update' object.pk %}"><i class="bi bi-pencil-square"></i></a>
    <a title="Delete" href="{% url 'references:authors-delete' object.pk %}"><i class="bi bi-trash"></i></a>
{% endblock dict_actions %}

{% block dict_create %}
    <a href="{% url 'references:authors-create' %}" class="btn btn-primary" style="width: 200px;">Add</a><br><br>
{% endblock dict_create %}

src/references/templates/list_book_formats.html
{% extends "references/list_template.html" %}

{% block title %}
    Book formats
{% endblock title %}

{% block page_header %}
    
{% endblock page_header %}

{% block dict_actions %}
    <a title="Edit" href="{% url 'references:book_formats-update' object.pk %}"><i class="bi bi-pencil-square"></i></a>
    <a title="Delete" href="{% url 'references:book_formats-delete' object.pk %}"><i class="bi bi-trash"></i></a>
{% endblock dict_actions %}

{% block dict_create %}
    <a href="{% url 'references:book_formats-create' %}" class="btn btn-primary" style="width: 200px;">Add</a><br><br>
{% endblock dict_create %}

src/references/templates/list_genres.html
{% extends "references/list_template.html" %}

{% block title %}
    Genres
{% endblock title %}

{% block page_header %}
    Genres
{% endblock page_header %}

{% block dict_actions %}
    <a title="Edit" href="{% url 'references:genres-update' object.pk %}"><i class="bi bi-pencil-square"></i></a>
    <a title="Delete" href="{% url 'references:genres-delete' object.pk %}"><i class="bi bi-trash"></i></a>
{% endblock dict_actions %}

{% block dict_create %}
    <a href="{% url 'references:genres-create' %}" class="btn btn-primary" >Add</a><br><br>
{% endblock dict_create %}

src/references/templates/list_publishers.html
{% extends "references/list_template.html" %}

{% block title %}
    Publishers
{% endblock title %}

{% block page_header %}
    Publishers
{% endblock page_header %}

{% block dict_actions %}
    <a title="Edit" href="{% url 'references:publishers-update' object.pk %}"><i class="bi bi-pencil-square"></i></a>
    <a title="Delete" href="{% url 'references:publishers-delete' object.pk %}"><i class="bi bi-trash"></i></a>
{% endblock dict_actions %}

{% block dict_create %}
    <a href="{% url 'references:publishers-create' %}" class="btn btn-primary">Add</a><br><br>
{% endblock dict_create %}

src/references/templates/list_series.html
{% extends "references/list_template.html" %}

{% block title %}
    Episodes
{% endblock title %}

{% block page_header %}
    Episodes
{% endblock page_header %}

{% block dict_actions %}
    <a title="Edit" href="{% url 'references:series-update' object.pk %}"><i class="bi bi-pencil-square"></i></a>
    <a title="Delete" href="{% url 'references:series-delete' object.pk %}"><i class="bi bi-trash"></i></a>
{% endblock dict_actions %}

{% block dict_create %}
    <a href="{% url 'references:series-create' %}" class="btn btn-primary" >Add</a><br><br>
{% endblock dict_create %}

src/references/templates/list_template.html
{% extends "template_main.html" %}
​
{% block title %}
    {{ block.super }}
{% endblock title %}
​
{% block page_header %}
    {{ block.super }}
{% endblock page_header %}
​
{% block main_content %}
​
<br>
​
    {% if page_obj.paginator.num_pages > 1 %}
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-end">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">&laquo;</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                    </li>
                {% endif %}
                    <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                {% endif %}
            </ul>
        </nav>
    {% else %}
        <br>
    {% endif %}
​
​
    <table class="table table-sm">
​
        <thead class="table-primary">
            <th>ID</th>
            <th>Name</th>
            <th>Actions</th>
        </thead>
        
        {% for object in page_obj %}
            <tr>
                <td>{{ object.pk }}</td>
                <td>{{ object.name }}</td>
                <td>
                    {% block dict_actions %}
                        {% comment %} <a title="Edit" href="{% url 'references:authors-update' object.pk %}"><i class="bi bi-pencil-square"></i></a>
                        <a title="Delete" href="{% url 'references:authors-delete' object.pk %}"><i class="bi bi-trash"></i></a> {% endcomment %}
                    {% endblock dict_actions %}
                </td>
            </tr>
        {% endfor %}
    </table>
    
    <br>
​
    {% block dict_create %}     
    {% endblock dict_create %}
​
{% endblock main_content %}

src/references/templates/template_main.html
{% extends "template_main.html" %}

{% block title %}
    {{ block.super }}
{% endblock title %}

{% block page_header %}
    {{ block.super }}
{% endblock page_header %}

{% block main_content %}

<br>

    {% if page_obj.paginator.num_pages > 1 %}
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-end">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">&laquo;</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                    </li>
                {% endif %}
                    <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                {% endif %}
            </ul>
        </nav>
    {% else %}
        <br>
    {% endif %}


    <table class="table table-sm table-striped table-hover">

        <thead class="table-primary">
            <th>ID</th>
            <th>Name</th>
            <th>Action</th>
        </thead>
        
        {% for object in page_obj %}
            <tr>
                <td>{{ object.pk }}</td>
                <td>{{ object.name }}</td>
                <td>
                    {% block dict_actions %}
                        {% comment %} <a title="Edit" href="{% url 'references:authors-update' object.pk %}"><i class="bi bi-pencil-square"></i></a>
                        <a title="Delete" href="{% url 'references:authors-delete' object.pk %}"><i class="bi bi-trash"></i></a> {% endcomment %}
                    {% endblock dict_actions %}
                </td>
            </tr>
        {% endfor %}
    </table>
    
    <br>

    {% block dict_create %}     
    {% endblock dict_create %}

{% endblock main_content %}