src/cart/urls.py
from django.urls import path
from cart import views


app_name = 'cart'

urlpatterns = [
    path('add-to-cart/', views.AddToCartView.as_view(), name='add-to-cart'),
    path('view-cart/', views.CartView.as_view(), name='view-cart'),
    path('update-cart/', views.UpdateCart.as_view(), name='update-cart'),
    path('delete-from-cart/<int:pk>/', views.DeleteFromCart.as_view(), name='delete-from-cart'),
]


# from django.urls import path
# from . import views

# app_name = 'cart'

# urlpatterns = [
#     path('add-to-cart/', views.UpdateCart.as_view(), name="add-to-cart"),
#     path('recalculate-cart/', views.RecalculateCart.as_view(), name="recalculate-cart")
# ]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as main_views
from references import urls as refs_urls
from users import urls as users_urls
from cart import urls as cart_urls


#from references.views import books_list
# from cart import views as cart_views


urlpatterns = [
    path('admin/', admin.site.urls), #http://127.0.0.1:8000/admin/
    path('', main_views.HomePage.as_view(), name='homepage'),
    path('books-catalog', main_views.BooksCatalog.as_view(), name='books-catalog'),
    path('references/', include(refs_urls, namespace='references')),
    path('users/', include(users_urls, namespace='users')),
    path('cart/', include(cart_urls, namespace='cart')),
    # path('books/', ref_views.BooksList.as_view(), name='books-list'),
    # path('books/<int:pk>/', ref_views.BookDetail.as_view(), name='book-detail'),
    # path('book-delete/<int:pk>/', ref_views.BookDelete.as_view(), name='book-delete'),
    # path('book-create/', ref_views.BookCreate.as_view(), name='book-create'),
    # path('book-update/<int:pk>/', ref_views.BookUpdate.as_view(),name="book-update"),
    # path('accs/', include(accs_urls)), 
    # path('cart/', include(cart_urls, namespace="cart")),
    # path('cart/', cart_views.HomePage.as_view(), name = "home-page")
    # path('home', ref_views.HomeList.as_view(), name='home'),
    # path('books/', views.books_list, name='books_list'), 
    # path('books/<int:pk>/', views.book_detail, name='book-detail'),
    # path('book-delete/<int:pk>/', views.book_delete, name='book-delete'),
    # path('book-create/', views.book_create, name='book-create'),
    # path('book-update/<int:pk>/', views.book_update, name='book-update'), 
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings .MEDIA_ROOT)  

    #path('books/<int:pk>', views.book_details)
    
    
#1.URL http://127.0.0.1:8000/cities/3/ (pk)
#2.GET http://127.0.0.1:8000/cities/?city_id=4...
#3.POST k:v, k:v    

src/references/urls.py
from django.urls import path
from . import views


app_name = 'references'

urlpatterns = [
    path('authors-list/', views.AuthorsList.as_view(), name='authors-list'),
    path('genres-list/', views.GenresList.as_view(), name='genres-list'),
    path('series-list/', views.SeriesList.as_view(), name='series-list'),
    path('publishers-list/', views.PublishersList.as_view(), name='publishers-list'),
    path('age_categories-list/', views.AgeCategoriesList.as_view(), name='age_categories-list'),
    # path('book_formats-list/', views.BookFormatsList.as_view(), name='book_formats-list'),

    path('authors-delete/<int:pk>/', views.AuthorsDelete.as_view(), name='authors-delete'),
    path('genres-delete/<int:pk>/', views.GenresDelete.as_view(), name='genres-delete'),
    path('series-delete/<int:pk>/', views.SeriesDelete.as_view(), name='series-delete'),
    path('publishers-delete/<int:pk>/', views.PublishersDelete.as_view(), name='publishers-delete'),
    path('age_categories-delete/<int:pk>/', views.AgeCategoriesDelete.as_view(), name='age_categories-delete'),
    # path('book_formats-delete/<int:pk>/', views.BookFormatsDelete.as_view(), name='book_formats-delete'),
    
    path('authors-update/<int:pk>/', views.AuthorsUpdate.as_view(), name='authors-update'),
    path('genres-update/<int:pk>/', views.GenresUpdate.as_view(), name='genres-update'),
    path('series-update/<int:pk>/', views.SeriesUpdate.as_view(), name='series-update'),
    path('publishes-update/<int:pk>/', views.PublishersUpdate.as_view(), name='publishers-update'),
    path('age_categories-update/<int:pk>/', views.AgeCategoriesUpdate.as_view(), name='age_categories-update'),
    # path('book_formats-update/<int:pk>/', views.BookFormatsUpdate.as_view(), name='book_formats-update'),
    
    path('authors-create/', views.AuthorsCreate.as_view(), name='authors-create'),
    path('genres-create/', views.GenresCreate.as_view(), name='genres-create'),
    path('series-create/', views.SeriesCreate.as_view(), name='series-create'),
    path('publishers-create/', views.PublishersCreate.as_view(), name='publishers-create'),
    path('age_categories-create/', views.AgeCategoriesCreate.as_view(), name='age_categories-create')
    # path('book_formats-create/', views.BookFormatsCreate.as_view(), name='book_formats-create')
]

src/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users import views


app_name = 'users'

urlpatterns = [
    path('create-user/', views.UserCreationView.as_view(), name='create-user'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('update-user/', views.UserUpdateView.as_view(), name='update-user'),
    path('logout/', views.UserLogoutView.as_view(), name='logout')
]



# from django.urls import path
# from . import views

# urlpatterns = [
#     # path('login/', views.login_view(), name='login'),
#     path('login/', views.MyLoginView.as_view(), name="login"), 
# ]

src/mainapp/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey, ManyToManyField
# from django.contrib.auth import models as auth_models



# Create your models here.
class BookCard(models.Model):
    name = models.CharField(
        verbose_name='Book name',
        max_length=80
    )
    
    picture = models.ImageField(
        verbose_name='Photo',
        upload_to='uploads/',
        null=True,
        blank=True
    )
    
    cost = models.DecimalField(
        verbose_name='Cost [USD]',
        max_digits=10,
        decimal_places=2,
        default=0.0
    )
    
    authors = ManyToManyField(
        'references.Authors',
        verbose_name='Authors',
        blank=True
    )

    series = ForeignKey(
        'references.Series',
        on_delete = models.PROTECT,
        blank=True,
        null=True
    )

    genres = ManyToManyField(
        'references.Genres',
        verbose_name='Genres',
        blank=True
    )

    year = models.SmallIntegerField(
        verbose_name='Year',
        default=1900
    )

    num_pages = models.SmallIntegerField(
        verbose_name='Pages amount',
        default=0
    )

    # book_format = ForeignKey(
    #     'references.BookFormats',
    #     on_delete = models.PROTECT,
    #     blank=True,
    #     null=True
    # )

    # isbn = models.CharField(
    #     verbose_name='ISBN',
    #     max_length=13,
    #     blank=True,
    #     null=True
    # )

    # weight = models.SmallIntegerField(
    #     verbose_name='Вес (гр)',
    #     default=0
    # )

    age_category = ForeignKey(
        'references.AgeCategories',
        on_delete = models.PROTECT,
        blank=True,
        null=True
    )

    publisher = ForeignKey(
        'references.Publishers',
        on_delete = models.PROTECT,
        blank=True,
        null=True
    )

    qty = models.SmallIntegerField(
        verbose_name='Amount',
        default=0
    )

    # is_active = models.BooleanField(
    #     verbose_name='available to order',
    #     default=True
    # )

    rating = models.FloatField(
        verbose_name='Rating',
        default=0.0  
    )

    create_date = models.DateTimeField(
        verbose_name='Date of creation',
        auto_now_add=True
    )

    update_date = models.DateTimeField(
        verbose_name='Date of last update',
        auto_now=True
    )

    def get_authors(self):
        return "\n".join([p.name for p in self.authors.all()])
    
    def get_genres(self):
        return "\n".join([p.name for p in self.genres.all()])

    def __str__(self):
        return self.name

src/references/models.py
from django.db import models
# Create your models here.


class Authors(models.Model):
    name = models.CharField(
        verbose_name='Author name',
        max_length=80,
        null=True,
        unique=True
    )

    def __str__(self):
        return self.name


class Series(models.Model):
    name = models.CharField(
        verbose_name='Book episode',
        max_length=80,
        null=True,
        unique=True
    )

    def __str__(self):
        return self.name


class Genres(models.Model):
    name = models.CharField(
        verbose_name='Book genre',
        max_length=80,
        null=True,
        unique=True
    )

    def __str__(self):
        return self.name


class Publishers(models.Model):
    name = models.CharField(
        verbose_name='Publisher',
        max_length=80,
        null=True,
        unique=True
    )

    def __str__(self):
        return self.name


class AgeCategories(models.Model):
    name = models.CharField(
        verbose_name='Age category',
        max_length=80,
        null=True,
        unique=True
    )

    def __str__(self):
        return self.name


# class BookFormats(models.Model):
#     name = models.CharField(
#         verbose_name='Формат книги',
#         max_length=80,
#         null=True,
#         unique=True
#    )

#     def __str__(self):
#         return self.name








# from django.db import models

# Create your models here.

# class Author(models.Model) :
#     #ID
#     name = models.CharField(
#         verbose_name="Name",
#         max_length=50, 
#         null=False,
#         blank=False) 
        
#     pic = models.ImageField(
#         verbose_name="Picture",
#         upload_to = "uploads/")

#     description = models.TextField(
#         verbose_name="Book description",
#         null=True,
#         blank=True)
    
#     created = models.DateTimeField(
#         verbose_name='Created date time',
#         auto_now=False,
#         auto_now_add=True)

#     updated = models.DateTimeField(
#         verbose_name='Updated date time',
#         auto_now=True)

 
#     def __str__(self):
#         return self.name

# # class AuthorPic(models.Model):
# #     name = "Picture name)",
# #     pic = models.ImageField,
# #     author = models.ForeignKey(Author)


# class Opinion(models.Model):
    
#     author = models.ForeignKey(
#         'references.Author',
#         verbose_name = 'Author',
#         on_delete = models.PROTECT,
#         related_name = 'Opinions')

#     Genre = models.CharField(
#         verbose_name="Genre name",
#         max_length=50)
    
#     Reviews = models.TextField(
#         verbose_name="Reviews",
#         null=True,
#         blank=True,
#         max_length=200)

#     Rating = models.PositiveIntegerField(
#         verbose_name="Rating value",
#         null=True,
#         blank=True)
    
#     def __str__(self):
#         return f'{self.author} {self.Genre} {self.Reviews} {self.Rating}'


    # we can describe tables in our DB by this Class (class Book)
    # ORM development
    # id/pk - django make automatically - columns = properties
    # class + () = object ; book_name = column with certain features
    # model field reference documentation
    # field options documentation


#class Home(models.Model):
    


# class Book(models.Model): 
#     book_name = models.CharField(
#         max_length=30,
#         verbose_name="Book title",
#         null=False,
#         blank=False)

#     pic = models.ImageField(
#         verbose_name="Picture",
#         upload_to = "uploads/",
#         null=True,
#         blank=True)

#     book_description = models.TextField(
#         verbose_name="Book description",
#         null=True,
#         blank=True)

#     author = models.CharField(
#         max_length=30,
#         verbose_name="Author name",
#         null=False,
#         blank=False)

#     genre_type = models.CharField(  
#         max_length=30,
#         verbose_name="Genre")
        

#     age = models.CharField(
#         verbose_name="Age category",
#         max_length=30,
#         null=True,
#         blank=True)

#     publishing = models.CharField(
#         verbose_name="Publishing",
#         max_length=30,
#         null=True,
#         blank=True)


#     rating = models.PositiveIntegerField(
#         verbose_name="Rating value",
#         null=True,
#         blank=True)

#     created = models.DateTimeField(
#         verbose_name='Created',
#         auto_now=False, # time of the last edditing
#         auto_now_add=True)

#     updated = models.DateTimeField(
#         verbose_name='Updated',
#         auto_now=True)


#     # class BookPic(models.Model):
#     #     name = "Picture name)",
#     #     pic = models.ImageField,
#     #     book = models.ForeignKey(Book)

#     def __str__(self): # OOP method
#         return self.book_name


# class Author(models.Model):

#     book = models.ForeignKey( # lesson 13
#         'references.Book', # the link to another class - Book 
#         verbose_name = 'Book',
#         on_delete = models.PROTECT,
#         related_name = 'authors') 

#     author_name = models.CharField(  #street in lesson 13 (2:10)
#         verbose_name="Author name",
#         max_length=30)

#     def __str__(self):
#         return f'{self.book.book_name} {self.author_name}' 
 

# class Genre(models.Model):

#     book = models.ForeignKey( 
#         'references.Book',  
#         verbose_name = 'Book',
#         on_delete = models.PROTECT,
#         related_name = 'genres') 

#     genre_type = models.CharField(  
#         verbose_name="Genre",
#         max_length=30)

#     def __str__(self):
#         return f'{self.book.book_name} {self.genre_type}' 


# class Age(models.Model):

#     book = models.ForeignKey( 
#         'references.Book', 
#         verbose_name = 'Book',
#         on_delete = models.PROTECT,
#         related_name = 'ages')

#     age_category = models.TextField(
#         verbose_name="Age category",
#         null=True,
#         blank=True)

#     def __str__(self):
#         return f'{self.book.book_name} {self.age_category}' 


# class Publishing(models.Model):

#     book = models.ForeignKey( 
#         'references.Book', 
#         verbose_name = 'Book',
#         on_delete = models.PROTECT,
#         related_name = 'publishings')

#     publishing = models.TextField(
#         verbose_name="Publishing",
#         null=True,
#         blank=True)

#     def __str__(self):
#         return f'{self.book.book_name} {self.publishing}' 

src/mainapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from mainapp import models


# Create your views here.
class HomePage(generic.TemplateView):
    model = models.BookCard
    template_name = "mainapp/homepage.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        books = self.model.objects.all().order_by('-pk')[0:9]
        context['objects'] = books
        return context


class BooksCatalog(generic.ListView):
    paginate_by = 12
    model = models.BookCard
    ordering = ['-pk']
    template_name = "mainapp/books_catalog.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        new_books = self.model.objects.all().order_by('-pk')[0:9]
        context['new_books'] = new_books
        return context

src/mainapp/templates/nav_bar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
 
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'homepage' %}"><i class="bi bi-house-door-fill"></i> homepage</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'books-catalog' %}"><i class="bi bi-bag-fill"></i> Catalog</a>
        </li>
        {% if perms.references.view_authors %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-book-fill"></i> References</a>
            <ul class="dropdown-menu" aria-labelledby="dropdown01">
              <li><a class="dropdown-item" href="{% url 'references:authors-list' %}">Authors</a></li>
              <li><a class="dropdown-item" href="{% url 'references:genres-list' %}">Genres</a></li>
              <li><a class="dropdown-item" href="{% url 'references:series-list' %}">Episodes</a></li>
              <li><a class="dropdown-item" href="{% url 'references:publishers-list' %}">Publishers</a></li>
              <li><a class="dropdown-item" href="{% url 'references:age_categories-list' %}">Age categories</a></li>
              {% comment %} <!-- <li><a class="dropdown-item" href="{% url 'references:book_formats-list' %}">Форматы книг</a></li> --> {% endcomment %}
            </ul>
          </li>
        {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle active text-info" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-circle"></i> 
            <b>
              {% if not user.is_authenticated %}
                
              {% else %}
                {% if user.first_name %}
                  {{ user.first_name }}
                {% else %}
                  {{ user.username }}
                {% endif %}
              {% endif %}
            </b>
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdown01">
            {% if not user.is_authenticated %}
              <li>
                <a class="dropdown-item" href="{% url 'users:login' %}?next={{ request.path }}"><i class="bi bi-box-arrow-in-right"></i> Login</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'users:create-user' %}"><i class="bi bi-person-plus-fill"></i> Registration</a>  
              </li>
            {% else %}
              <li>
                <a class="dropdown-item" href="{% url 'users:update-user' %}"><i class="bi bi-info-circle"></i> Profile</a>
              </li>
              </li>
                <a class="dropdown-item" href="#"><i class="bi bi-bag"></i> Orders</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'users:logout' %}"><i class="bi bi-box-arrow-left"></i> Logout</a>
              </li>
            {% endif %}
          </ul>
        </li>
      </ul>
    </div>
      <a href="{% url 'cart:view-cart' %}" class="btn btn-success">
        <i class="bi bi-cart4"></i>
          {% if request.session.books_in_cart %}
            <span class="badge bg-light text-dark">
                {{ request.session.books_in_cart }}
            </span>
          {% endif %}
      </a>
  </div>
</nav>

src/mainapp/templates/template_main.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />

    <title>My Book Store - {% block title %}{% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css"
    />

    <meta name="theme-color" content="#563d7c" />

    <!-- Custom styles for this template -->
    <style>
      body {
        padding-top: 5rem;
        {% comment %} background: url("{% static 'mainapp/img/book_store_bg.jpg' %}"); {% endcomment %}
      }
      
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>

  <body>

    {% include 'nav_bar.html' %}

    <main role="main" class="container">
      <div class="starter-template">
        
        <h3><b>{% block page_header %}{% endblock page_header %}</b></h3>

        {% block main_content %}{% endblock main_content %}
      </div>
    </main>
    <!-- /.container -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
      crossorigin="anonymous"
    ></script>
  </body>
</html>