src/cart/urls.py
from django.urls import path
from cart import views


app_name = 'cart'

urlpatterns = [
    path('add-to-cart/', views.AddToCartView.as_view(), name='add-to-cart'),
    path('view-cart/', views.CartView.as_view(), name='view-cart'),
    path('update-cart/', views.UpdateCart.as_view(), name='update-cart'),
    path('delete-from-cart/<int:pk>/', views.DeleteFromCart.as_view(), name='delete-from-cart'),
]


# from django.urls import path
# from . import views

# app_name = 'cart'

# urlpatterns = [
#     path('add-to-cart/', views.UpdateCart.as_view(), name="add-to-cart"),
#     path('recalculate-cart/', views.RecalculateCart.as_view(), name="recalculate-cart")
# ]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as main_views
from references import urls as refs_urls
from users import urls as users_urls
from cart import urls as cart_urls


#from references.views import books_list
# from cart import views as cart_views


urlpatterns = [
    path('admin/', admin.site.urls), #http://127.0.0.1:8000/admin/
    path('', main_views.HomePage.as_view(), name='homepage'),
    path('books-catalog', main_views.BooksCatalog.as_view(), name='books-catalog'),
    path('references/', include(refs_urls, namespace='references')),
    path('users/', include(users_urls, namespace='users')),
    path('cart/', include(cart_urls, namespace='cart')),
    # path('books/', ref_views.BooksList.as_view(), name='books-list'),
    # path('books/<int:pk>/', ref_views.BookDetail.as_view(), name='book-detail'),
    # path('book-delete/<int:pk>/', ref_views.BookDelete.as_view(), name='book-delete'),
    # path('book-create/', ref_views.BookCreate.as_view(), name='book-create'),
    # path('book-update/<int:pk>/', ref_views.BookUpdate.as_view(),name="book-update"),
    # path('accs/', include(accs_urls)), 
    # path('cart/', include(cart_urls, namespace="cart")),
    # path('cart/', cart_views.HomePage.as_view(), name = "home-page")
    # path('home', ref_views.HomeList.as_view(), name='home'),
    # path('books/', views.books_list, name='books_list'), 
    # path('books/<int:pk>/', views.book_detail, name='book-detail'),
    # path('book-delete/<int:pk>/', views.book_delete, name='book-delete'),
    # path('book-create/', views.book_create, name='book-create'),
    # path('book-update/<int:pk>/', views.book_update, name='book-update'), 
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings .MEDIA_ROOT)  

    #path('books/<int:pk>', views.book_details)
    
    
#1.URL http://127.0.0.1:8000/cities/3/ (pk)
#2.GET http://127.0.0.1:8000/cities/?city_id=4...
#3.POST k:v, k:v    

src/mainapp/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey, ManyToManyField
# from django.contrib.auth import models as auth_models



# Create your models here.
class BookCard(models.Model):
    name = models.CharField(
        verbose_name='Book name',
        max_length=80
    )
    
    picture = models.ImageField(
        verbose_name='Photo',
        upload_to='uploads/',
        null=True,
        blank=True
    )
    
    cost = models.DecimalField(
        verbose_name='Cost [USD]',
        max_digits=10,
        decimal_places=2,
        default=0.0
    )
    
    authors = ManyToManyField(
        'references.Authors',
        verbose_name='Authors',
        blank=True
    )

    series = ForeignKey(
        'references.Series',
        on_delete = models.PROTECT,
        blank=True,
        null=True
    )

    genres = ManyToManyField(
        'references.Genres',
        verbose_name='Genres',
        blank=True
    )

    year = models.SmallIntegerField(
        verbose_name='Year',
        default=1900
    )

    num_pages = models.SmallIntegerField(
        verbose_name='Pages amount',
        default=0
    )

    # book_format = ForeignKey(
    #     'references.BookFormats',
    #     on_delete = models.PROTECT,
    #     blank=True,
    #     null=True
    # )

    # isbn = models.CharField(
    #     verbose_name='ISBN',
    #     max_length=13,
    #     blank=True,
    #     null=True
    # )

    # weight = models.SmallIntegerField(
    #     verbose_name='Вес (гр)',
    #     default=0
    # )

    age_category = ForeignKey(
        'references.AgeCategories',
        on_delete = models.PROTECT,
        blank=True,
        null=True
    )

    publisher = ForeignKey(
        'references.Publishers',
        on_delete = models.PROTECT,
        blank=True,
        null=True
    )

    qty = models.SmallIntegerField(
        verbose_name='Amount',
        default=0
    )

    # is_active = models.BooleanField(
    #     verbose_name='available to order',
    #     default=True
    # )

    rating = models.FloatField(
        verbose_name='Rating',
        default=0.0  
    )

    create_date = models.DateTimeField(
        verbose_name='Date of creation',
        auto_now_add=True
    )

    update_date = models.DateTimeField(
        verbose_name='Date of last update',
        auto_now=True
    )

    def get_authors(self):
        return "\n".join([p.name for p in self.authors.all()])
    
    def get_genres(self):
        return "\n".join([p.name for p in self.genres.all()])

    def __str__(self):
        return self.name

src/mainapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from mainapp import models


# Create your views here.
class HomePage(generic.TemplateView):
    model = models.BookCard
    template_name = "mainapp/homepage.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        books = self.model.objects.all().order_by('-pk')[0:9]
        context['objects'] = books
        return context


class BooksCatalog(generic.ListView):
    paginate_by = 12
    model = models.BookCard
    ordering = ['-pk']
    template_name = "mainapp/books_catalog.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        new_books = self.model.objects.all().order_by('-pk')[0:9]
        context['new_books'] = new_books
        return context

src/mainapp/templates/mainapp/books_card.html
{% extends "template_main.html" %}
{% load static %}
{% block title %}
    BookEshop
{% endblock title %}

{% block page_header %}
  Books catalogue
{% endblock page_header %}
{% block main_content %}

<br>

{% if page_obj.paginator.num_pages > 1 %}
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-end">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page=1">&laquo;</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
      </li>
      {% endif %}
      <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
      {% endif %}
    </ul>
  </nav>
{% endif %}

<div class="container">
{% for object in page_obj %}
  <div class="row">
    <h5 class="alert-primary"><b>{{ object.name }}</b></h5>
    <div class="col col-md-auto">
        <img src=
          {% if not object.picture %}
            <!-- "{% static 'mainapp/img/no_book_photo.png' %}" -->
          {% else %}
            "media/{{ object.picture }}"
          {% endif %}
        class="img-fluid" width="250px">

    </div>
    <div class="col">
      <table>
        <tr>
          <td>
            <b>Authors:</b>
          </td>
          <td>
            {% for author in object.authors.all %}
              {{ author.name }}
              {% if author != object.authors.last %}, {% endif %}
            {% endfor %}
          </td>
        </tr>

        <tr>
          <td>
            <b>Genres:</b>
          </td>
          <td>
            {% for genre in object.genres.all %}
              {{ genre.name }}
              {% if genre != object.genres.last %}, {% endif %}
            {% endfor %}
          </td>
        </tr>

        <tr>
          <td>
            <b>Episodes:</b>
          </td>
          <td>
             {% if object.series %}{{ object.series }}{% endif %}
          </td>
        </tr>

        <tr>
          <td>
            <b>Publisher:</b>
          </td>
          <td>
             {% if object.publisher %}{{ object.publisher }}{% endif %}
          </td>
        </tr>

        <tr>
          <td>
            <b>Year:</b>
          </td>
          <td>
             {% if object.year %}{{ object.year }}{% endif %}
          </td>
        </tr>

        <tr>
          <td>
            <b>Number of pages:</b>
          </td>
          <td>
             {% if object.num_pages %}{{ object.num_pages }}{% endif %}
          </td>
        </tr>
        
{% comment %} <!-- 
        <tr>
          <td>
            <b>Формат:</b>
          </td>
          <td>
             {% if object.book_format %}{{ object.book_format }}{% endif %}
          </td>
        </tr> -->

        <!-- <tr>
          <td>
            <b>ISBN:</b>
          </td>
          <td>
             {% if object.isbn %}{{ object.isbn }}{% endif %}
          </td>
        </tr> -->
<!-- 
        <tr>
          <td>
            <b>Вес (гр.):</b>
          </td>
          <td>
             {% if object.weight %}{{ object.weight }}{% endif %}
          </td>
        </tr> --> {% endcomment %}

        <tr>
          <td>
            <b>Age category:</b>
          </td>
          <td>
             {% if object.age_category %}{{ object.age_category }}{% endif %}
          </td>
        </tr>
      </table>

    </div>
    <div class="col col-md-auto">
      <h5>{{ object.cost }} USD</h5>
      Availability {{ object.qty }}
      <br><br>
      <a href="#" class="btn btn-success btn-sm text-bottom {% if not object.is_active %}disabled{% endif %}"><i class="bi bi-cart4"></i> Buy </a>
    </div>
  </div>
  <br>
{% endfor %}
</div>

{% endblock main_content %}


{% comment %} <table class="table">
  {% for object in object_list %}
    <tr>
      <td>
        <div class="container">
        <img src=
          {% if not object.picture %}
            No picture
            <!-- "{% static 'mainapp/img/no_book_photo.png'%}" -->
          {% else %}
            "media/{{ object.picture }}"
          {% endif %}
        class="img-fluid" width="250px">
        
          <div class="img-stamp" style="position: absolute; top: 0px; left: 0px; background-color: transparent;">
            <img src="{% static 'mainapp/img/new.png'%}" class="img-fluid" width="96">
          </div>
        </div>
      </td>
      <td>
        <h6><b>Name: {{ object.name }}</b></h6>
        Authors:
          {% for author in object.authors.all %}
            {{ author.name }}
            {% if author != object.authors.last %}, {% endif %}
          {% endfor %}
        
        <br>Episode: {{ object.series }}
        <br>Genre:
          {% for genre in object.genres.all %}
            {{ genre.name }}
            {% if genre != object.genres.last %}, {% endif %}
          {% endfor %}
        <br>Year: {{ object.year }}
        <br>Number of pages: {{ object.num_pages }}
        <!-- <br>Формат: {{ object.book_format }}
        <br>ISBN: {{ object.isbn }}
        <br>Вес: {{ object.weight }} гр. -->
        <br>Age category: {{ object.age_category }}
        <br>Publisher: {{ object.publisher }}
        <br>Availability: {{ object.qty }} шт.
      </td>
      <td>
        <h5>{{ object.cost }} USD </h5>
      </td>
    </tr>
  {% endfor %}
</table>  {% endcomment %}

src/mainapp/templates/mainapp/books_catalog.html
{% extends "template_main.html" %}
{% load static %}
{% block title %}

{% endblock title %}
{% block page_header %}
  Books catalogue
{% endblock page_header %}
{% block main_content %}

<br>

{% if page_obj.paginator.num_pages > 1 %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                </li>
            {% endif %}
                <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
            {% endif %}
        </ul>
    </nav>
{% else %}
    <br>
{% endif %}

<div class="row row-cols-1 row-cols-md-4 g-4">
    {% for object in page_obj %}
        <div class="col">
            <div class="card h-100 shadow bg-body text-center">
                    <img src=
                        {% if not object.picture %}
                            "{% static 'mainapp/img/no_book_photo.png' %}"
                        {% else %}
                            "/media/{{ object.picture }}"
                        {% endif %}
                    class="shadow bg-body rounded-3 mx-auto d-block" style="width: 150px" alt="...">
                <div class="card-body">
                    <h6 class="card-title">{{ object.name }}</h6>
                    <p class="card-text">
                        <i>
                            {% for author in object.authors.all %}
                                {{ author.name }}
                                {% if author != object.authors.last %}, {% endif %}
                            {% endfor %}
                        </i>
                    </p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">
                        <h5>{{ object.cost }}USD</h5>
                        Rating: {{ object.rating }}<br>
                        Availability: {{ object.qty }} <br>
                        {% if object.is_active %}
                            <a href="{% url 'cart:add-to-cart' %}?book={{ object.pk }}&next={{ request.get_full_path }}"
                                class="btn btn-success btn-sm text-bottom
                                {% if not object.is_active %}
                                    disabled
                                {% endif %}">
                                <i class="bi bi-cart4"></i> Buy
                            </a>
                        {% else %}
                        Not available
                        {% endif %}
                    </small>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% comment %} 
<br>

<div class="container">
{% for object in page_obj %}
    <div class="row">
        <h5 class="alert-primary"><b>{{ object.name }}</b></h5>
        <div class="col col-md-auto">
            <img src=
            {% if not object.picture %}
                "{% static 'mainapp/img/no_book_photo.png' %}"
            {% else %}
                "media/{{ object.picture }}"
            {% endif %}
            class="img-fluid" width="250px">

        </div>
        <div class="col">
        <table>
            <tr>
            <td>
                <b>Authors:</b>
            </td>
            <td>
                {% for author in object.authors.all %}
                {{ author.name }}
                {% if author != object.authors.last %}, {% endif %}
                {% endfor %}
            </td>
            </tr>

            <tr>
            <td>
                <b>Genres:</b>
            </td>
            <td>
                {% for genre in object.genres.all %}
                {{ genre.name }}
                {% if genre != object.genres.last %}, {% endif %}
                {% endfor %}
            </td>
            </tr>

            <tr>
            <td>
                <b>Episode:</b>
            </td>
            <td>
                {% if object.series %}{{ object.series }}{% endif %}
            </td>
            </tr>

            <tr>
            <td>
                <b>Publishers:</b>
            </td>
            <td>
                {% if object.publisher %}{{ object.publisher }}{% endif %}
            </td>
            </tr>

            <tr>
            <td>
                <b>Year:</b>
            </td>
            <td>
                {% if object.year %}{{ object.year }}{% endif %}
            </td>
            </tr>

            <tr>
            <td>
                <b>Number of pages:</b>
            </td>
            <td>
                {% if object.num_pages %}{{ object.num_pages }}{% endif %}
            </td>
            </tr>

            <!-- <tr>
            <td>
                <b>Формат:</b>
            </td>
            <td>
                {% if object.book_format %}{{ object.book_format }}{% endif %}
            </td>
            </tr> -->

            <!-- <tr>
            <td>
                <b>ISBN:</b>
            </td>
            <td>
                {% if object.isbn %}{{ object.isbn }}{% endif %}
            </td>
            </tr>
            <tr>
            <td>
                <b>Вес (гр.):</b>
            </td>
            <td>
                {% if object.weight %}{{ object.weight }}{% endif %}
            </td>
            </tr> -->

            <tr>
            <td>
                <b>Age category:</b>
            </td>
            <td>
                {% if object.age_category %}{{ object.age_category }}{% endif %}
            </td>
            </tr>
        </table>

        </div>
        <div class="col col-md-auto">
        <h5>{{ object.cost }} BYN</h5>
        Availability: {{ object.qty }} 
        <br><br>
        <a href="#" class="btn btn-success btn-sm text-bottom {% if not object.is_active %}disabled{% endif %}"><i class="bi bi-cart4"></i>Buy</a>
        </div>
    </div>
    <br>
{% endfor %}
</div> {% endcomment %}




{% comment %} <table class="table">
  {% for object in object_list %}
    <tr>
      <td>
        <div class="container">
        <img src=
          {% if not object.picture %}
            <!-- "{% static 'mainapp/img/no_book_photo.png'%}" -->
            No picture
          {% else %}
            "media/{{ object.picture }}"
          {% endif %}
        class="img-fluid" width="250px">
        
          <div class="img-stamp" style="position: absolute; top: 0px; left: 0px; background-color: transparent;">
            <img src="{% static 'mainapp/img/new.png'%}" class="img-fluid" width="96">
          </div>
        </div>
      </td>
      <td>
        <h6><b>Name: {{ object.name }}</b></h6>
        Authors:
          {% for author in object.authors.all %}
            {{ author.name }}
            {% if author != object.authors.last %}, {% endif %}
          {% endfor %}
        
        <br>Episode: {{ object.series }}
        <br>Genre:
          {% for genre in object.genres.all %}
            {{ genre.name }}
            {% if genre != object.genres.last %}, {% endif %}
          {% endfor %}
        <br>Year: {{ object.year }}
        <br>Number of pages: {{ object.num_pages }}
        <!-- <br>Формат: {{ object.book_format }}
        <br>ISBN: {{ object.isbn }}
        <br>Вес: {{ object.weight }} гр. -->
        <br>Age category: {{ object.age_category }}
        <br>Publisher: {{ object.publisher }}
        <br>Availability: {{ object.qty }} 
      </td>
      <td>
        <h5>{{ object.cost }}USD </h5>
      </td>
    </tr>
  {% endfor %}
</table> {% endcomment %}

{% endblock main_content %}

src/mainapp/templates/mainapp/homepage.html
{% extends "template_main.html" %}

{% load static %}

{% block title %}
Homepage
{% endblock title %}

{% comment %} <!-- {% block page_header %}

    <table class="table table-borderless">
      <tr>
        <td>
          <img src="{% static 'mainapp/img/books_banner.png' %}" class="img-fluid rounded mx-auto d-block" alt="..."  style="max-height: 10rem;">
        </td>
        <td>
          <img src="{% static 'mainapp/img/news_banner01.png' %}" class="img-fluid rounded mx-auto d-block" alt="..."  style="max-height: 10rem;">
        </td>
        <td>
          <img src="{% static 'mainapp/img/books_banner.png' %}" class="img-fluid rounded mx-auto d-block" alt="..."  style="max-height: 10rem;">
        </td>
      </tr>
    </table>

{% endblock page_header %} --> {% endcomment %}

{% block main_content %}

<br>
<br>
  
<div id="carouselExampleControls" class="carousel slide carousel-dark" data-bs-ride="carousel">
  <div class="carousel-inner">
    {% for object in objects %}
      <div class="carousel-item {% if object == objects.0 %}active{% endif %}">
        <div class="card mb-3 border-light text-dark container-fluid" style="max-width: 480px; text-align: center;">
          <div class="row g-0">
            <div class="col-md-4">
              <img src="{% if not object.picture %}{% static 'mainapp/img/no_book_photo.png'%}{% else %}media/{{ object.picture }}{% endif %}" class="img-fluid">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{ object.name }}</h5>
                <p class="card-text">{{ object.get_authors }}</p>
                <p class="card-text"><small class="text-muted">
                  <a href="{% url 'cart:add-to-cart' %}?book={{ object.pk }}&next={{ request.get_full_path }}"
                    class="btn btn-success btn-sm text-bottom
                    {% if not object.is_active %}
                      disabled
                    {% endif %}">
                    <i class="bi bi-cart4"></i> Buy
                  </a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"  data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Back</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"  data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

{% endblock main_content %}