src/cart/urls.py
from django.urls import path
from cart import views


app_name = 'cart'

urlpatterns = [
    path('add-to-cart/', views.AddToCartView.as_view(), name='add-to-cart'),
    path('view-cart/', views.CartView.as_view(), name='view-cart'),
    path('update-cart/', views.UpdateCart.as_view(), name='update-cart'),
    path('delete-from-cart/<int:pk>/', views.DeleteFromCart.as_view(), name='delete-from-cart'),
]


# from django.urls import path
# from . import views

# app_name = 'cart'

# urlpatterns = [
#     path('add-to-cart/', views.UpdateCart.as_view(), name="add-to-cart"),
#     path('recalculate-cart/', views.RecalculateCart.as_view(), name="recalculate-cart")
# ]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as main_views
from references import urls as refs_urls
from users import urls as users_urls
from cart import urls as cart_urls


#from references.views import books_list
# from cart import views as cart_views


urlpatterns = [
    path('admin/', admin.site.urls), #http://127.0.0.1:8000/admin/
    path('', main_views.HomePage.as_view(), name='homepage'),
    path('books-catalog', main_views.BooksCatalog.as_view(), name='books-catalog'),
    path('references/', include(refs_urls, namespace='references')),
    path('users/', include(users_urls, namespace='users')),
    path('cart/', include(cart_urls, namespace='cart')),
    # path('books/', ref_views.BooksList.as_view(), name='books-list'),
    # path('books/<int:pk>/', ref_views.BookDetail.as_view(), name='book-detail'),
    # path('book-delete/<int:pk>/', ref_views.BookDelete.as_view(), name='book-delete'),
    # path('book-create/', ref_views.BookCreate.as_view(), name='book-create'),
    # path('book-update/<int:pk>/', ref_views.BookUpdate.as_view(),name="book-update"),
    # path('accs/', include(accs_urls)), 
    # path('cart/', include(cart_urls, namespace="cart")),
    # path('cart/', cart_views.HomePage.as_view(), name = "home-page")
    # path('home', ref_views.HomeList.as_view(), name='home'),
    # path('books/', views.books_list, name='books_list'), 
    # path('books/<int:pk>/', views.book_detail, name='book-detail'),
    # path('book-delete/<int:pk>/', views.book_delete, name='book-delete'),
    # path('book-create/', views.book_create, name='book-create'),
    # path('book-update/<int:pk>/', views.book_update, name='book-update'), 
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings .MEDIA_ROOT)  

    #path('books/<int:pk>', views.book_details)
    
    
#1.URL http://127.0.0.1:8000/cities/3/ (pk)
#2.GET http://127.0.0.1:8000/cities/?city_id=4...
#3.POST k:v, k:v    

src/cart/models.py
from django.db import models
from django.contrib.auth import models as auth_models
from mainapp import models as main_models

# from django.db import models
# from django.contrib.auth import get_user_model
# User = get_user_model()

class CustomerCart(models.Model): #basket settings
    customer = models.ForeignKey(
        auth_models.User,
        # User, 
        on_delete=models.PROTECT, #if delete user - controversion
        verbose_name='Customer',
        related_name='customer_carts',
        blank = False,
        null=True
    )

    create_date=models.DateTimeField(
        verbose_name='Date of creation',
        auto_now=True
    )

    update_date = models.DateTimeField(
        verbose_name='Date of change',
        auto_now=True
    )

#threshold - doscounts - dinamic parameter

    # @property
    # def total_summ(self):
    #     all_books = self.books.all()
    #     total = 0
    #     for book in all_books:
    #         total += book.total_price
    #     return total

    @property
    def get_books_count(self):
        count = 0
        
        for book in self.books_in_cart.all():
            count += book.qty
        
        return count

    @property
    def get_total_price(self):
        total_price = 0
        
        for book in self.books_in_cart.all():
            total_price += book.get_total_price
        
        return total_price

    def __str__(self):
        return f"cart ID {self.pk}"



class BooksInCart(models.Model): #link to the things what clients buying
    customer_cart = models.ForeignKey(
        'CustomerCart',
        on_delete=models.PROTECT,
        verbose_name='Basket',
        related_name='books_in_cart',
        blank=False,
        null=True   
    )

    # cart = models.ForeignKey(
    #     Cart,
    #     verbose_name="Cart",
    #     related_name="books",
    #     on_delete=models.CASCADE)

    book_card = models.ForeignKey(
        main_models.BookCard,
        on_delete=models.PROTECT,
        verbose_name='Book',
        related_name='book_cards'
    )

    qty = models.IntegerField(
        verbose_name='Amount'
    )

    # book = models.ForeignKey(
    #     "references.Book",
    #     verbose_name="Book in cart",
    #     on_delete=models.PROTECT)

    # quantity = models.IntegerField("Quantity", default=1)

    # price = models.DecimalField(
    #     "Price", 
    #     max_digits=5,
    #     decimal_places=2)

    price = models.DecimalField(
        verbose_name='Cost',
        max_digits=5,
        decimal_places=2
    )

    create_date = models.DateTimeField(
        verbose_name='Date of creation',
        auto_now_add=True
    )

    update_date = models.DateTimeField(
        verbose_name='Date of changing',
        auto_now=True
    )
    
    @property
    def get_total_price(self):
        return self.qty * self.price

# @property
# def total_price(self):
#     return self.book.price * self.quantity

# def __str__(self):
#         return f"BookInCart ID {self.pk} {self.book.book_name} quantity {self.quantity} price {self.price}"

    def __str__(self):
        return f'{self.book_card}, {self.qty}, {self.price} USD'
    

src/cart/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.contrib.auth import models as auth_models
# from django.views.generic import TemplateView, DetailView, RedirectView
# templateview - show template page
# from references import models as ref_models
# from . import models
# from . import utils 
from cart import models
from mainapp import models as main_models
from cart import utils


# class HomePage(TemplateView):
#     template_name = 'cart\home-page.html'

#     def get_context_data (self, **kwargs):
#         context = super() .get_context_data(**kwargs)
#         context ["books"] = ref_models.Book.objects.all().order_by ("-pk")[:5]   
#         return context

class AddToCartView(generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        book_pk = self.request.GET.get('book')

        if book_pk:
            current_cart_pk = self.request.session.get('current_cart_pk')
            current_customer = None if self.request.user.is_anonymous else self.request.user
            current_cart, cart_created = models.CustomerCart.objects.get_or_create(
                pk=current_cart_pk,
                defaults={'customer': current_customer}
            )
            
            if cart_created:
                self.request.session['current_cart_pk'] = current_cart.pk
                current_cart.save()
            else:
                utils.check_cart_owner(current_cart, current_customer)

            book = main_models.BookCard.objects.get(pk=book_pk)
            book_in_cart, created = models.BooksInCart.objects.get_or_create(
                customer_cart=current_cart,
                book_card=book,
                defaults={'qty': 1, 'price': book.cost}
            )

            if not created:
                book_in_cart.qty += 1
                book_in_cart.save()
            
            self.request.session['books_in_cart'] = current_cart.get_books_count

        return self.request.GET.get('next')


class CartView(generic.DetailView):
    model = models.CustomerCart
    template_name = 'cart/view_cart.html'

    def get_object(self):
        current_cart = None
        current_cart_pk = self.request.session.get('current_cart_pk')
        
        if current_cart_pk:
            current_cart = models.CustomerCart.objects.get(pk=current_cart_pk)
            current_customer = None if self.request.user.is_anonymous else self.request.user
            utils.check_cart_owner(current_cart, current_customer)

        return current_cart


class DeleteFromCart(generic.DeleteView):
    model = models.BooksInCart
    template_name = 'cart/delete_from_cart.html'
    success_url = reverse_lazy('cart:view-cart')

    def delete(self, request, *args, **kwargs):
        obj = super().delete(request)
        utils.update_books_count(self.request)
        return obj


class UpdateCart(generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        action = utils.update_items_in_cart(self.request)
        if action =='checkout':
            return reverse('homepage')
        else:
            return reverse('cart:view-cart')






# class UpdateCart(DetailView):
#     model = models.Cart
#     def get_object(self, *args, **kwargs):
#         book_id = self.request.GET.get('book')
#         if not book_id:
#             current_cart_pk = self.request.session.get('current_cart_pk')
#             if current_cart_pk:
#                 current_cart = models.Cart.objects.filter(pk = current_cart_pk).first()
#                 return current_cart or []
#             return []
#         else:
#             current_cart_pk = self.request.session.get('current_cart_pk')
#             current_customer = self.request.user 
#             if current_customer.is_anonymous:
#                 current_customer=None
#             current_cart, cart_created = models.Cart.objects.get_or_create(
#                 pk = current_cart_pk,
#                 defaults= {'customer': current_customer}
#             )
#             print(cart_created, current_cart.pk)
#             if cart_created:
#                 self.request.session['current_cart_pk'] = current_cart.pk
#                 self.request.session['current_cart_pk']
#             book = ref_models.Book.objects.get(pk=book_id)
#             book_in_cart, book_created = models.BookInCart.objects.get_or_create(
#                 cart = current_cart,
#                 book = book,
#                 defaults = {'quantity': 1, 'price': book.price}
#             )
#             if not book_created:
#                 book_in_cart.quantity += 1
#                 book_in_cart.save()
#         return current_cart


# class RecalculateCart(RedirectView):
#     def get_redirect_url(self, *args, **kwargs):
#         return_urls = {
#             'checkout': reverse("cart:checkout")
#         }
#         current_cart_pk, cart_items = utils.harvest_data(self)
#         if not current_cart_pk:
#             return reverse ("cart:add_to_cart")
#         action = utils.update_items_in_cart(current_cart_pk, cart_items_from_form)
#         # action = checkout or recalculate
#         if action == "checkout":
#             url = reverse ("cart:checkout")
#         else:
#             reverse("cart:add_to_cart")
#         return url

src/cart/templates/cart/add-book.html
{% comment %} <!-- {% block main_content %}

    <h1> {{ request.session.current_cart_pk }} </h1>
    {{ object }} <br> <hr>
    <h1> Books in the Cart </h1>
    <form action="{% url 'cart:recalculate-cart' %}" method="POST">

    <table class="table" >
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Price per unit</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total</th>
            </tr>
        </thead>
        {% for book_in_cart in object.books.all %}
            <tr>
                <td>{{ book_in_cart.name }}</td>
                <td></td>
                <td><input type="number" min=0 name="book_in_cart_{{book_in_cart.pk}}" value="{{ book_in_cart.quantity}}"> </td>
                <td>{{ book_in_cart.total_price }}</td>
            </tr>
        {% endfor %} 
            <tr>
                <td colspan ="3"><b> Total </b></td>
                <td> <b>  {{ object.total_summ }} </b></td>
            </tr>
    </table>
    <button type="submit" name="btn" class ="btn btn-success" value ="recalculate">Recalculate</button>
    <button type="submit" name="btn" class ="btn btn-danger" value="checkout">Checkout</button>
</form>

{% endblock main_content %}     --> {% endcomment %}

src/cart/templates/cart/add-city.html
{% block main_content %}

    <h1> {{ request.session.current_cart_pk }} </h1>
    {{ object }} <br> <hr>
    {% for author_in_cart in object.authors.all %}
    {{ author_in_cart.author }} <br>
    {{ author_in_cart.quantity }} <br>
    {% endfor %} 
{% endblock main_content %}    

src/cart/templates/cart/delete-from-cart.html
{% extends "template_main.html" %}

{% block title %}
    Removing an item from the cart
{% endblock title %}

{% block page_header %}
    Are you sure you want to delete this item {{ object.pk }} <b><i>({{ object}})</i></b>?
{% endblock page_header %}

{% block main_content %}
    
    <br>

    <form action="" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger" >Delete</button>
        <a onclick="history.back()" class="btn btn-secondary" >Back</a>
    </form>
    
{% endblock main_content %}

src/cart/templates/cart/view_cart.html
{% extends "template_main.html" %}
{% load static %}
{% block title %}
    Basket
{% endblock title %}
{% block page_header %}
  Basket items
{% endblock page_header %}
{% block main_content %}

<br>

{% if request.session.books_in_cart %}
  <form action="{% url 'cart:update-cart' %}">
    <table class="table table-sm table-striped table-hover">
      <thead class="table-primary text-center align-middle">
        <th></th>
        <th>Name</th>
        <th>Amount</th>
        <th>Price</th>
        <th>Total price</th>
        <th></th>
      </thead>
      <tbody>
        {% for book in object.books_in_cart.all %}
          <tr class="align-middle">
            <td>
              <img src="/media/{{ book.book_card.picture }}" class="shadow bg-body rounded-3" style="width: 30px;" alt="...">
            </td>
            <td>
              {{ book.book_card.name }}
            </td>
            <td>
              <input class="text-center" size="5" type="number" min="0" name="{{ book.pk }}" value="{{ book.qty }}">
            </td>
            <td class="text-center">
              {{ book.price }} USD
            </td>
            <td class="text-center">
              {{ book.get_total_price }} USD
            </td>
            <td class="text-center">
              <a title="Remove" href="{% url 'cart:delete-from-cart' book.pk %}">
                <i class="bi bi-trash text-danger"></i>
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
      <tfoot>
        <tr class="align-middle">
          <td colspan="2"><b>Summary</b></td>
          <td class="text-center"><b>{{ object.get_books_count }}</td>
          <td></td>
          <td class="text-center"><b>{{ object.get_total_price }} USD</b></td>
          <td></td>
          </tr>
      </tfoot>
    </table>
    <br>
    <button type="submit" name="btn" value="recalculate" class="btn btn-primary">Recalculate</button>
    <button type="submit" name="btn" value="checkout" class="btn btn-success">Make order</button>
  </form>
{% else %}
  <h1 class="text-danger"><b><i>Basket is empty</i></b></h1>
{% endif %}

{% endblock main_content %}